data:
  # path to pickled bedroom
  data_path: /shared/data/new_room_data/bedroom_new_multi_img/
  out_path:  tests/data/scene_outputs
  list_path: None

model:
  cat:
    start_token: 52
    stop_token: 51
    pad_token: 50
  # Todo: look up max_obj_num

  coor:
    start_token: 203
    stop_token: 202
    pad_token: 201


  orient:
    start_token: 363
    stop_token: 362
    pad_token: 361

  relation:
    start_token: 4
    stop_token: 3
    pad_token: 2

  dim:
    shape_cond: false
    text_cond: false
    start_token: 83
    stop_token: 82
    pad_token: 81


  max_seq_len: 120
  max_obj_num: 100
  cat_num: 28
  emb_dim: 256
  dim_fwd: 256
  num_heads: 8
  num_blocks: 8
  dropout: 0.3

train:
  batch_size: 128
  epochs: 2000
  lr: 0.0003
  resume : null 
  l2: 0.001
  lr_restart: 10000
  warmup: 2000