data:
  # path to pickled bedroom
  data_path: /shared/data/new_room_data/bedroom_new_multi_img
  out_path:  tests/data/scene_outputs
  list_path: None

model:
  cat:
    shape_cond: True
    text_cond : False
#    bedroom
#    start_token: 52
#    stop_token: 51
#    pad_token: 50
#    living
    start_token: 41
    stop_token: 40
    pad_token: 39


  # Todo: look up max_obj_num

  coor:
    shape_cond : False
    text_cond: True
    start_token: 203
    stop_token: 202
    pad_token: 201

  orient:
    shape_cond: True
    text_cond: False
    start_token: 363
    stop_token: 362
    pad_token: 361

  relation:
    start_token: 4
    stop_token: 3
    pad_token: 2


  dim:
    shape_cond: True
    start_token: 83
    stop_token: 82
    pad_token: 81

  max_seq_len: 120

  max_seq_len: 120
  max_obj_num: 30
  cat_num: 28
  emb_dim: 512
  dim_fwd: 1024
  num_heads: 8
  num_blocks: 8
  dropout: 0.3

train:
  aug:
    jitter_list: [0.,  0.05,  0.1,  0.15,  0.2, 0.25, 0.3]
    rotation_list: [0 , 90, 180, 270]
  batch_size: 64
  epochs: 2000
  lr: 0.0003
  resume : null
  l2: 0.001
  lr_restart: 20000
  warmup: 10000

test:
  num_samples: 2
  # sample outputs or choose deterministically?
  probabilistic: False
  model_file:  null #lightning_logs/version_226/checkpoints/last.ckpt
  log_dir: lightning_logs/version_20/out/